
daemon off;

error_log /dev/stdout info;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            # low latency tuning
            sync 0;
            wait_key on;
            wait_video on;
            drop_idle_publisher 5s;
        }
    }
}

http {
    root /www/static;
    access_log /dev/stdout combined;

    server {
        listen 8080;

        location / {
            return 200 "RTMP server running\n";
        }
    }
}
